// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQtiK29HenOI4MAmPGnB16Ryry3uX3ZM',
    appId: '1:492118983584:web:fd59e781d1389086d65ac5',
    messagingSenderId: '492118983584',
    projectId: 'face-scanner-b4dfb',
    authDomain: 'face-scanner-b4dfb.firebaseapp.com',
    storageBucket: 'face-scanner-b4dfb.firebasestorage.app',
    measurementId: 'G-FFBEX40650',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiKWwq0qFtEqKZZ0AuIGgnmbDdJBTq02Q',
    appId: '1:492118983584:android:b43cadbc194f9516d65ac5',
    messagingSenderId: '492118983584',
    projectId: 'face-scanner-b4dfb',
    storageBucket: 'face-scanner-b4dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsZtKb7XgwkFu0x82ea9HBIMAwnqLjIs',
    appId: '1:492118983584:ios:96c91b182f0dbcc9d65ac5',
    messagingSenderId: '492118983584',
    projectId: 'face-scanner-b4dfb',
    storageBucket: 'face-scanner-b4dfb.firebasestorage.app',
    iosBundleId: 'com.faceyoga.fitness.beautyscore.analysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADsZtKb7XgwkFu0x82ea9HBIMAwnqLjIs',
    appId: '1:492118983584:ios:c6f13b29ea559a75d65ac5',
    messagingSenderId: '492118983584',
    projectId: 'face-scanner-b4dfb',
    storageBucket: 'face-scanner-b4dfb.firebasestorage.app',
    iosBundleId: 'com.example.faceScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOQtiK29HenOI4MAmPGnB16Ryry3uX3ZM',
    appId: '1:492118983584:web:5e9a4673310cca4ad65ac5',
    messagingSenderId: '492118983584',
    projectId: 'face-scanner-b4dfb',
    authDomain: 'face-scanner-b4dfb.firebaseapp.com',
    storageBucket: 'face-scanner-b4dfb.firebasestorage.app',
    measurementId: 'G-1F4D9VKDTX',
  );
}
